ssl:
- hosts: ["*.localhost.test", "default"]
  key: example.key
  cert: example.crt
extranet:
- host: "*.localhost.test"
  portal_host: 'extranet.localhost.test'
  cas_url: https://login.atomshare.net/cas
proxy:
- hosts: [localhost.test, www.localhost.test]
  target_host: localhost
  target_port: 8000
  sslonly: true
- host: secret.localhost.test
  target_host: localhost
  target_port: 8000
  protect: true
